version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
    groups:
      bundler:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - '*'
