import globals from 'globals';
import pluginJs from '@eslint/js';
import tseslint from 'typescript-eslint';
import userscripts from 'eslint-plugin-userscripts';

export default [
	{
		ignores: [
			'**/node_modules/**',
			'**/dist/**',
			'**/build/**',
			'**/*.min.js',
			'**/*.min.cjs',
			'**/*.min.mjs',
			// Coverage output (generated by Jest —  not source code)
			'coverage/**',
			// Legacy ESLint config file (not source code)
			'.eslintrc.js',
			// Third-party / vendored library files (not authored code)
			'beautify-css-mod.js',
			'beautify.js',
			'css.js',
			'strava-balance/binary.js',
			'strava-balance/buffer-5.6.1/**',
			'strava-balance/Strava-AddBalance.js',
			// Previously ignored
			'SuperchargedLocalDirectoryWebUI.user.js',
			'codemirror.js',
			'SteamDB-Dark-Mode.user.css',
			'WahooFitnessDarkMode.user.css',
			'codemirror.min.js',
			'ESPN-DarkMode.user.css',
			'Skial-CustomTheme.user.css',
		],
	},
	{
		files: ['**/*.{js,mjs,cjs,ts}'],
		languageOptions: {
			ecmaVersion: 'latest',
			globals: {
				...globals.browser,
				...globals.greasemonkey,
				...globals.jquery,
			},
			parserOptions: {
				projectService: true,
				tsconfigRootDir: import.meta.dirname,
			},
		},
	},
	{
		files: ['**/*.js'],
		languageOptions: { sourceType: 'script' },
	},
	// Chrome / WebExtension files
	{
		files: ['YouTubeVolumeControl/**/*.js', 'YouTubeTVVolumeControl/**/*.js'],
		languageOptions: {
			globals: {
				chrome: 'readonly',
			},
		},
	},
	pluginJs.configs.recommended,
	...tseslint.configs.recommendedTypeChecked,
	// Typed rules that are impractical for untyped JS userscripts (every DOM
	// query / JSON.parse / GM callback produces `any`, flooding these rules).
	// The valuable type-aware rules (await-thenable, no-floating-promises,
	// no-misused-promises, only-throw-error, require-await) remain active.
	{
		files: ['**/*.{js,mjs,cjs}'],
		rules: {
			'@typescript-eslint/no-base-to-string': 'off',
			'@typescript-eslint/no-redundant-type-constituents': 'off',
			'@typescript-eslint/no-unnecessary-type-assertion': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',
			'@typescript-eslint/no-unsafe-unary-minus': 'off',
			'@typescript-eslint/restrict-plus-operands': 'off',
			'@typescript-eslint/restrict-template-expressions': 'off',
			'@typescript-eslint/unbound-method': 'off',
		},
	},
	// Global rule overrides (applied after tseslint to ensure precedence)
	{
		files: ['**/*.{js,mjs,cjs,ts}'],
		rules: {
			// Treat _ prefix as intentionally unused (standard convention)
			'@typescript-eslint/no-unused-vars': [
				'error',
				{
					argsIgnorePattern: '^_',
					caughtErrorsIgnorePattern: '^_',
					destructuredArrayIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],
		},
	},
	// CommonJS files — must come after tseslint to properly override its rules
	{
		files: ['**/*.cjs', '**/*.test.cjs'],
		languageOptions: {
			globals: {
				...globals.node,
			},
			sourceType: 'commonjs',
		},
		rules: {
			'@typescript-eslint/no-require-imports': 'off',
		},
	},
	// Jest test files — add Jest globals (describe, it, expect, …)
	// Scoped to __tests__/ only so Mocha files at the root are unaffected.
	{
		files: ['**/__tests__/**/*.test.cjs'],
		languageOptions: {
			globals: {
				...globals.jest,
			},
		},
	},
	{
		files: ['**/*.user.js'],
		plugins: {
			userscripts: {
				rules: userscripts.rules,
			},
		},
		rules: {
			...userscripts.configs.recommended.rules,
			'userscripts/compat-grant': 'error',
			'userscripts/compat-headers': 'error',
		},
		settings: {
			userscriptVersions: {
				greasemonkey: '*',
				tampermonkey: '*',
				violentmonkey: '*',
			},
		},
	},
];
