# This GitHub Actions workflow is named "black-formatter" and is triggered on push and pull request events.
# It has read permissions for repository contents.
#
# The workflow defines a single job named "black-linter" that runs on the latest Ubuntu runner.
#
# Steps:
# 1. Harden Runner:
#    - Uses the "step-security/harden-runner" action (specific commit) to enhance security.
#    - Disables sudo, blocks egress traffic, and allows specific endpoints (files.pythonhosted.org, github.com, pypi.org).
#
# 2. Checkout Code:
#    - Uses the "actions/checkout" action (specific commit) to check out the repository code.
#
# 3. Run Black Formatter:
#    - Uses the "psf/black" action (specific commit) to run the Black code formatter on the repository.
name: black-formatter

on: [push, pull_request]
permissions:
  contents: read

jobs:
  black-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            files.pythonhosted.org:443
            github.com:443
            pypi.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: psf/black@1b2427a2b785cc4aac97c19bb4b9a0de063f9547 # stable
