name: GitHub Pages - Generate XML sitemap

on:
  push:
    branches: [main]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            github.com:443

      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@eb8db82126ee30619883c8c43e8c49ec14ebd6dc # v1.10.1
        with:
          base-url-path: https://userstyles.github.typpi.online/
          additional-extensions: doc docx ppt pptx js css json xml xlsx xls pdf md markdown txt

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
          echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          title: "Automated sitemap update"
          body: >
            Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap)
            GitHub action. Automated pull-request generated by the
            [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
